name: life_os_productivity
description: "Sistem Pengelola Hidup Profesional - Fokus Produktivitas & Mimpi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lucide_icons: ^0.257.0 
  google_fonts: ^6.1.0
  flutter_riverpod: ^2.4.9
  uuid: ^3.0.7
  
  # Database Hive (Lebih stabil untuk setup sekarang)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # UI & Animation
  percent_indicator: ^4.2.3
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true